/**
 * Master Reference Data Constants & In-Memory Fallbacks
 */

export const DEFAULT_MANUFACTURERS = [
  {
    name: 'Square D',
    slug: 'square-d',
    aliases: ['Square D by Schneider Electric', 'Schneider Electric Square D', 'SQD'],
    website_domain: 'se.com',
  },
  {
    name: 'Eaton',
    slug: 'eaton',
    aliases: ['Eaton Cutler-Hammer', 'Cutler Hammer', 'Eaton Electrical'],
    website_domain: 'eaton.com',
  },
  {
    name: 'Siemens',
    slug: 'siemens',
    aliases: ['Siemens Energy & Automation', 'Siemens Industry'],
    website_domain: 'siemens.com',
  },
  {
    name: 'Hubbell',
    slug: 'hubbell',
    aliases: ['Hubbell Wiring Device-Kellems', 'Hubbell Incorporated', 'Kellems'],
    website_domain: 'hubbell.com',
  },
  {
    name: 'Leviton',
    slug: 'leviton',
    aliases: ['Leviton Manufacturing Co.', 'Leviton Mfg'],
    website_domain: 'leviton.com',
  },
  {
    name: 'Klein Tools',
    slug: 'klein-tools',
    aliases: ['Klein', 'Klein Tools Inc'],
    website_domain: 'kleintools.com',
  },
  {
    name: 'Milwaukee Tool',
    slug: 'milwaukee-tool',
    aliases: ['Milwaukee', 'Milwaukee Electric Tool'],
    website_domain: 'milwaukeetool.com',
  },
  {
    name: 'DeWalt',
    slug: 'dewalt',
    aliases: ['DeWalt Industrial Tool Co', 'Stanley Black & Decker DeWalt'],
    website_domain: 'dewalt.com',
  },
];

export const DEFAULT_FIELD_DEFINITIONS = [
  {
    field_key: 'partNumber',
    label: 'Part Number',
    field_type: 'text',
    field_group: 'Basic',
    editable: false,
    char_limit: 50,
    required: true,
    help_text: 'Unique distributor/internal part identifier',
  },
  {
    field_key: 'manufacturerName',
    label: 'Manufacturer Name',
    field_type: 'lov',
    field_group: 'Basic',
    editable: true,
    char_limit: 255,
    required: true,
    help_text: 'Resolved official manufacturer from UniCat vocabulary',
  },
  {
    field_key: 'brandName',
    label: 'Brand Name',
    field_type: 'lov',
    field_group: 'Basic',
    editable: true,
    char_limit: 255,
    required: false,
    help_text: 'Resolved product brand associated with manufacturer',
  },
  {
    field_key: 'manufacturerPartNumber',
    label: 'Manufacturer Part Number (MPN)',
    field_type: 'text',
    field_group: 'Basic',
    editable: true,
    char_limit: 100,
    required: false,
    help_text: 'Exact manufacturer catalog number or model code',
  },
  {
    field_key: 'classpath',
    label: 'Taxonomy Classpath',
    field_type: 'lov',
    field_group: 'Basic',
    editable: true,
    char_limit: 500,
    required: true,
    help_text: '3-tier Dept > Class > Fine taxonomy categorization',
  },
  {
    field_key: 'shortDesc',
    label: 'Short Description',
    field_type: 'text',
    field_group: 'Descriptions',
    editable: true,
    char_limit: 150,
    required: true,
    help_text: 'Concise, noun-first technical specification description (max 150 chars)',
  },
  {
    field_key: 'mobileDesc',
    label: 'Mobile Description',
    field_type: 'text',
    field_group: 'Descriptions',
    editable: true,
    char_limit: 80,
    required: false,
    help_text: 'Ultra-compact mobile app summary description (max 80 chars)',
  },
  {
    field_key: 'invoiceDesc',
    label: 'Invoice Description',
    field_type: 'text',
    field_group: 'Descriptions',
    editable: true,
    char_limit: 40,
    required: false,
    help_text: 'ERP invoice & packing slip format (max 40 chars)',
  },
  {
    field_key: 'longDesc1',
    label: 'Long Description',
    field_type: 'textarea',
    field_group: 'Descriptions',
    editable: true,
    char_limit: 4000,
    required: false,
    help_text: 'Comprehensive technical specification text',
  },
  {
    field_key: 'retailDesc',
    label: 'Retail Description',
    field_type: 'textarea',
    field_group: 'Descriptions',
    editable: true,
    char_limit: 4000,
    required: false,
    help_text: 'Consumer-friendly retail catalog overview',
  },
];
